research/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^[/]*$', views.index, name='index'),
    url(r'^students/$', views.StudentIndexView.as_view(), name='student'),
    url(r'^projects/$', views.ProjectIndexView.as_view(), name='project'),
    url(r'^projects/add$', views.ProjectCreateView.as_view(), name='project_add'),
    url(r'^projects/update/(?P<pk>[0-9]+)$', views.ProjectUpdateView.as_view(), name='project_update'),
    url(r'^projects/delete/(?P<pk>[0-9]+)$', views.ProjectDeleteView.as_view(), name='project_delete'),
    url(r'^research_labs/$', views.ResearchLabIndexView.as_view(), name='researchlab'),
    url(r'^project_detail/(?P<pk>[0-9]+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
    url(r'^student_detail/(?P<pk>[0-9]+)/$', views.StudentDetailView.as_view(), name='student_detail'),
    url(r'^research_lab/add/$', views.ResearchLabCreate.as_view(), name='research_lab_add'),
    url(r'^research_lab/update/(?P<pk>[0-9]+)/$', views.ResearchLabUpdate.as_view(), name='research_lab_update'),
    url(r'^research_lab/delete/(?P<pk>[0-9]+)/$', views.ResearchLabDelete.as_view(), name='research_lab_delete'),

]

tj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^research/', include('research.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

research/models.py
from django.db import models

# Create your models here.


#class Question(models.Model):
#    question_text = models.CharField(max_length=200)
#    pub_date = models.DateTimeField('date published')


#class Choice(models.Model):
#    question = models.ForeignKey(Question, on_delete=models.CASCADE)
#    choice_text = models.CharField(max_length=200)
#    votes = models.IntegerField(default=0)


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.id, filename)

class Project(models.Model):
    title = models.CharField(max_length=1024)
    abstract = models.TextField(max_length=32767)
    paper = models.FileField(upload_to=user_directory_path)
    director = models.ForeignKey('LabDirector', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.title

class Student(models.Model):
    last_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    student_id = models.CharField(max_length=10)
    cookie = models.TextField(max_length=1000)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return "%s, %s" % (self.last_name, self.first_name)

class ResearchLab(models.Model):
    lab_name = models.CharField(max_length=50)
    lab_description = models.TextField(max_length=1000)
    
    def __str__(self):
        return self.lab_name

class LabDirector(models.Model):
    last_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    lab = models.ForeignKey(ResearchLab, on_delete=models.SET_NULL, null=True)

    
    def __str__(self):
        return "%s, %s" % (self.last_name, self.first_name)

research/forms.py
from django.forms import ModelForm
from .models import ResearchLab, Student, Project
from django.forms.models import inlineformset_factory


class ResearchLabForm(ModelForm):
    class Meta:
        model = ResearchLab
        fields = ['lab_name', 'lab_description']


StudentsFormSet = inlineformset_factory(Student, Project)

research/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, "research/index.html")

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Student, Project, ResearchLab


class ProjectIndexView(generic.ListView):
    model = Project

class ProjectDetailView(generic.DetailView):
    model = Project

class StudentIndexView(generic.ListView):
    model = Student

class StudentDetailView(generic.DetailView):
    model = Student

class ProjectCreateView(generic.CreateView):
    model = Project
    fields = ['title', 'abstract', 'paper', 'director']
    success_url = '/research/projects/'

class ProjectUpdateView(generic.UpdateView):
    model = Project
    fields = ['title', 'abstract', 'paper', 'director']
    success_url = '/research/projects/'

class ProjectDeleteView(generic.DeleteView):
    model = Project
    fields = ['title', 'abstract', 'paper', 'director']
    success_url = '/research/projects/'

class ResearchLabIndexView(generic.ListView):
    model = ResearchLab

class ResearchLabCreate(generic.CreateView):
    model = ResearchLab
    fields = ['lab_name', 'lab_description']
    success_url = '/research/research_labs/'

class ResearchLabUpdate(generic.UpdateView):
    model = ResearchLab
    fields = ['lab_name', 'lab_description']
    success_url = '/research/research_labs/'


class ResearchLabDelete(generic.DeleteView):
    model = ResearchLab
    fields = ['lab_name', 'lab_description']
    success_url = '/research/research_labs/'

research/templates/research/index.html
{% extends "research/main_template.html" %}

{% block title %}TJ reSearch{% endblock %}

{% block content %}
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">TJ reSearch</h1>
          <p>TJ Senior Research projects are collected here. You can browse by lab,
          search by keyword, lab and topic, and also enter or edit your own 
          research project information.</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Browse</h2>
            <p>Browse through projects by research lab. You can access project summaries, abstracts,
	      posters, talk slides, full reports and detailed project information.</p>
            <p><a class="btn btn-secondary" href="{% url 'researchlab' %}" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Search</h2>
            <p>Full-text search of project reports, keywords, abstracts. Or perform an advanced search
	      by lab, results, equipment, open questions and rating.</p>
            <p><a class="btn btn-secondary" href="search.html" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Edit</h2>
            <p>Authenticate with ion and edit the information for your research project. Upload your proposal,
	      abstract, research paper, poster, talk slides. List awards won. Create a list of open questions. Provide
	      contact info.</p>
            <p><a class="btn btn-secondary" href="edit.html" role="button">View details &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->
{% endblock %}

research/templates/research/lists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<ul>
    <li><a href="./students/">Student list</a></li>
    <li><a href="./projects/">Project list</a></li>
</ul>
</body>
</html>

research/templates/research/main_template.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  
    <title>{% block title %}Title{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{% static 'research/jumbotron.css'%}" rel="stylesheet" type="text/css">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main role="main">
    {% block content %}
        Body Content
    {% endblock %}


    </main>

    <footer class="container">
      <p>&copy; tjhsst 2017-2018</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  </body>
</html>

research/templates/research/project_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm Delete</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</body>
</html>

research/templates/research/project_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project Detail</title>
</head>
<body>
    {{ project.title }}: {{ project.student_set.first.first_name }} {{ project.student_set.first.last_name }}
</body>
</html>

research/templates/research/project_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Research Lab Form</title>
</head>
<body>
<h1>Project Update</h1>
<form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
</body>
</html>

research/templates/research/project_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project List</title>
</head>
<body>
{% if project_list %}
    <ul>
        {%  for project in project_list %}
            <li> <a href="{% url 'project_detail' project.id %}">{{ project.title }}</a>
            <a href="{% url 'project_update' project.id %}">Edit</a>
            <a href="{% url 'project_delete' project.id %}">Delete</a></li>
        {%  endfor %}
    </ul>
{%  else %}
    <p>No project data available</p>
{% endif %}
<p><a href="{% url 'project_add' %}">Add Project</a></p>
</body>
</html>

research/templates/research/researchlab_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm Delete</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</body>
</html>

research/templates/research/researchlab_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Research Lab Form</title>
</head>
<body>
<h1>Research Lab Update</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
</body>
</html>

research/templates/research/researchlab_list.html
{% extends 'research/main_template.html' %}
{% block title %}Research Labs{% endblock %}
{% block content %}

    {% if researchlab_list %}
        <div class="container">
            <h2>Browse by Research Labs</h2>
            <!-- Example row of columns -->
            {% for lab in researchlab_list|dictsort:"lab_name" %}
                {% if forloop.first %}<div class="row">{% endif %}
                <div class="col-md-4">
                    <div class="card border-primary  mb-3" style="max-width: 20rem;">
                        <div class="card-header">{{ lab.lab_name }}</div>
                        <div class="card-body">
                            <p class="card-text">{{ lab.lab_description|truncatechars:250 }}
                                <!--<a href="{% url 'research_lab_delete' lab.id %}">delete</a>-->
                            </p>
                            <br/>Director{{ lab.labdirector_set.all|pluralize }}:
                            {% for director in lab.labdirector_set.all|dictsort:"last_name" %}
                                {{ director.last_name }}
                                {%  ifnotequal forloop.last True %}
                                    ,
                                {% endifnotequal %}
                            {% endfor %}
                        </div>
                        </div>
                    </div>
                {% if forloop.counter|divisibleby:3 %}
                    </div>
                    <div class="row">
                {% endif %}
            {% if forloop.last %}
                </div>
            {% endif %}
            {% endfor %}

            <hr>
        </div> <!-- /container -->
    {% endif %}
    <div class="container">
        <p><a href="{% url 'research_lab_add' %}">Add a Lab</a></p>
    </div>
{% endblock %}

research/templates/research/researchlab_list_bk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
{% if researchlab_list %}
    <ul>
        {%  for lab in researchlab_list %}
            <li> <a href="{% url 'research_lab_update' lab.id %}">{{ lab.lab_name }}</a>:
                {{ lab.lab_description }} <a href="{% url 'research_lab_delete' lab.id %}">delete</a></li>
        {%  endfor %}
    </ul>
{%  else %}
    <p>No lab data available</p>
{% endif %}
<p><a href="{% url 'research_lab_add' %}">Add a Lab</a></p>
</body>
</html>

research/templates/research/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Detail</title>
</head>
<body>
    {{ student.first_name }} {{ student.last_name }}: {{ student.project.title }}
</body>
</html>

research/templates/research/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
{% if student_list %}
    <ul>
        {%  for student in student_list %}
            <li> <a href="{% url 'student_detail' student.id %}">{{ student.first_name }} {{ student.last_name }} </a></li>
        {%  endfor %}
    </ul>
{%  else %}
    <p>No student data available</p>
{% endif %}
</body>
</html>